% This is an autogenerated sample test for file apply_fullconnect.m
classdef testapply_fullconnect < matlab.unittest.TestCase

    methods (Test)

        function test_apply_fullconnect(testCase)
            % Specify the input(s) of
            % apply_fullconnect
            layerResults = evalin("base", "layerResults");
            filterbanks = evalin("base", "filterbanks");
            biasvectors = evalin("base", "biasvectors");
            inarray = layerResults{1, 16};
            filterbank = filterbanks{1, 17};
            biasvals = biasvectors{1, 17};

            % Specify the expected output(s) of
            % apply_fullconnect
            expected_outarray = layerResults{1,17};

            % Exercise the function apply_fullconnect
            actual_outarray = apply_fullconnect(inarray, filterbank, biasvals);
            disp(actual_outarray);
            testCase.verifyEqual(actual_outarray, expected_outarray);
        end
    end
end