% This is an autogenerated sample test for file apply_relu.m
classdef testapply_relu < matlab.unittest.TestCase

    methods (Test)

        function test_apply_relu(testCase)
            layerResults = evalin("base", "layerResults"); 
            % Specify the input(s) of
            % apply_relu
            inarray = layerResults{1, 2};

            % Specify the expected output(s) of
            % apply_relu
            expected_outarray = layerResults{1, 3};

            % Exercise the function apply_relu
            actual_outarray = apply_relu(inarray);
            disp(actual_outarray);
            testCase.verifyEqual(actual_outarray, expected_outarray);
        end
    end
end