% This is an autogenerated sample test for file apply_convolve.m
classdef testapply_convolve < matlab.unittest.TestCase


    methods (Test)

        function test_apply_convolve(testCase)
            layerResults = evalin("base", "layerResults");
            filterbanks = evalin("base", "filterbanks");
            biasvectors = evalin("base", "biasvectors");
            % Specify the input(s) of
            % apply_convolve
            inarray = layerResults{1, 1};
            filterbank = filterbanks{1, 2};
            biasvals = biasvectors{1, 2};

            % Specify the expected output(s) of
            % apply_convolve
            expected_outarray = layerResults{1, 2};

            % Exercise the function apply_convolve
            actual_outarray = apply_convolve(inarray, filterbank, biasvals);
            disp(actual_outarray);
            testCase.verifyEqual(actual_outarray, expected_outarray);
        end
    end
end