% This is an autogenerated sample test for file apply_softmax.m
classdef testapply_softmax < matlab.unittest.TestCase
    methods (Test)

        function test_apply_softmax(testCase)
            %load('cifar10testdata.mat' , 'layerResults');
            %load('CNNparameters.mat');
            % Specify the input(s) of
            % apply_softmax
            layerResults = evalin("base", "layerResults"); 
            inarray = layerResults{1,17};

            % Specify the expected output(s) of
            % apply_softmax
            expected_outarray = layerResults{1,18};

            % Exercise the function apply_softmax
            actual_outarray = apply_softmax(inarray);

            testCase.verifyEqual(actual_outarray, expected_outarray);
            %disp(testCase.verifyEqual(actual_outarray, expected_outarray));
            disp(actual_outarray);
        end
    end
end