% This is an autogenerated sample test for file apply_imnormalize.m
classdef testapply_imnormalize < matlab.unittest.TestCase

    methods (Test)

        function test_apply_imnormalize(testCase)
            layerResults = evalin("base", "layerResults"); 
            imrgb = evalin("base", "imrgb"); 
            % Specify the input(s) of
            % apply_imnormalize
            inarray = double(imrgb);

            % Specify the expected output(s) of
            % apply_imnormalize
            expected_outarray = layerResults{1,1};

            % Exercise the function apply_imnormalize
            actual_outarray = apply_imnormalize(inarray);
            disp(actual_outarray);
            testCase.verifyEqual(actual_outarray, expected_outarray);
        end
    end
end